name: Yiban

on:
  workflow_dispatch:
  #schedule:
  #- cron: '0 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    
    - name: Set ENV
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Yiban
      run: |
        python main.py
